[2024-10-25T07:15:47.690+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T07:15:48.274+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_generator.generate_account_dim_data scheduled__2024-10-24T00:00:00+00:00 [queued]>
[2024-10-25T07:15:48.325+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_generator.generate_account_dim_data scheduled__2024-10-24T00:00:00+00:00 [queued]>
[2024-10-25T07:15:48.334+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-25T07:15:48.534+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2024-10-24 00:00:00+00:00
[2024-10-25T07:15:48.803+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-25T07:15:48.835+0000] {standard_task_runner.py:72} INFO - Started process 152 to run task
[2024-10-25T07:15:48.845+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_generator', 'generate_account_dim_data', 'scheduled__2024-10-24T00:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_generator.py', '--cfg-path', '/tmp/tmp_x0vtx6b']
[2024-10-25T07:15:48.849+0000] {standard_task_runner.py:105} INFO - Job 204: Subtask generate_account_dim_data
[2024-10-25T07:15:49.897+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_generator.generate_account_dim_data scheduled__2024-10-24T00:00:00+00:00 [running]> on host d993b9f280d5
[2024-10-25T07:15:50.874+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='saisunny' AIRFLOW_CTX_DAG_ID='account_dim_generator' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-24T00:00:00+00:00'
[2024-10-25T07:15:50.897+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-25T07:15:50.899+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-25T07:15:50.904+0000] {logging_mixin.py:190} INFO - Current task name:generate_account_dim_data state:running start_date:2024-10-25 07:15:48.275863+00:00
[2024-10-25T07:15:50.931+0000] {logging_mixin.py:190} INFO - Dag name:account_dim_generator and current dag run status:running
[2024-10-25T07:15:50.962+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T07:15:51.772+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 rows has been generated successfully!
[2024-10-25T07:15:51.923+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-25T07:15:52.411+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T07:15:52.416+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_generator, task_id=generate_account_dim_data, run_id=scheduled__2024-10-24T00:00:00+00:00, execution_date=20241024T000000, start_date=20241025T071548, end_date=20241025T071552
[2024-10-25T07:15:52.747+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-25T07:15:52.838+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-25T07:15:52.886+0000] {logging_mixin.py:190} INFO - Dag name:account_dim_generator queued_at:2024-10-25 07:14:57.142511+00:00
[2024-10-25T07:15:52.930+0000] {logging_mixin.py:190} INFO - Task hostname:d993b9f280d5 operator:PythonOperator
[2024-10-25T07:15:53.128+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-25T07:15:53.662+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-25T07:15:53.793+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-25T07:15:54.055+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
